version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["docker/**/Dockerfile"]

[[analyzers]]
name = "php"

  [analyzers.meta]
  bootstrap_files = ["composer"]

[[transformers]]
name = "php-cs-fixer"